/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.gConta.Cliente;
import business.ConfiguraFacil;

import java.awt.*;
import java.awt.event.*;
import java.sql.SQLException;
import java.util.List;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author Pedro
 */
public class NovoClienteFrame extends javax.swing.JFrame {

    ConfiguraFacil cf;
    ClientesFrame to_update;
    RegistaEncomendaFrame to_update2;


    private void registar_btnActionPerformed(ActionEvent e) throws Exception {
        String nome = this.nome_txt.getText();
        String telemovel = this.telemovel_txt.getText();
        String email = this.email_txt.getText();

        try {
            if (!nome.equals("") && !email.equals("")){
                this.cf.registaCliente(nome, Integer.parseInt(telemovel), email);

                List<Cliente> list = this.cf.getClientes();
                if (to_update!=null) {
                    this.to_update.updateTable(list);
                    this.to_update.updateList(list);
                }
                if (to_update2!=null) {
                    this.to_update2.updateClientesTable(list);
                    this.to_update2.updateList(list);
                }
                JOptionPane.showMessageDialog(new JFrame(), "Cliente registado com sucesso", "Cliente Registado", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(new JFrame(), "Preencha todos os campos.", "Campos por preencher", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        }
        catch (NumberFormatException e1){
            JOptionPane.showMessageDialog(new JFrame(), "Introduza um nº de telemóvel válido.", "Telemóvel inválido", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void sair_btnActionPerformed(ActionEvent e) {
        this.dispose();
    }


    /**
     * Creates new form NovoClienteFrame
     */
    public NovoClienteFrame(ConfiguraFacil cf, ClientesFrame f, RegistaEncomendaFrame f2) {
        initComponents();
        this.cf = cf;
        this.to_update=f;
        this.to_update2=f2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Pedro Moreira
    private void initComponents() {
        nome_txt = new JTextField();
        telemovel_txt = new JTextField();
        email_txt = new JTextField();
        registar_btn = new JButton();
        label1 = new JLabel();
        label2 = new JLabel();
        label3 = new JLabel();
        sair_btn = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Cliente");
        Container contentPane = getContentPane();

        //---- nome_txt ----
        nome_txt.setToolTipText("");

        //---- registar_btn ----
        registar_btn.setText("Registar");
        registar_btn.addActionListener(e -> {
            try {
                registar_btnActionPerformed(e);
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        });

        //---- label1 ----
        label1.setText("Nome");

        //---- label2 ----
        label2.setText("Telem\u00f3vel");

        //---- label3 ----
        label3.setText("E-mail");

        //---- sair_btn ----
        sair_btn.setText("Sair");
        sair_btn.addActionListener(e -> sair_btnActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sair_btn, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                    .addComponent(registar_btn)
                    .addContainerGap())
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addComponent(label2)
                        .addComponent(label3)
                        .addComponent(label1))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(telemovel_txt)
                        .addComponent(nome_txt)
                        .addComponent(email_txt, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(30, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(nome_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(label1))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(telemovel_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(label2))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(email_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(label3))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(registar_btn)
                        .addComponent(sair_btn))
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Pedro Moreira
    private JTextField nome_txt;
    private JTextField telemovel_txt;
    private JTextField email_txt;
    private JButton registar_btn;
    private JLabel label1;
    private JLabel label2;
    private JLabel label3;
    private JButton sair_btn;
    // End of variables declaration//GEN-END:variables
}
