/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.ConfiguraFacil;
import business.gConfig.Configuracao;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author Pedro
 */
public class RegistaEncomendaFrame extends javax.swing.JFrame {

    ConfiguraFacil cf;
    Configuracao config;
    /**
     * Creates new form RegistaEncomendaFrame
     */
    private void novo_cliente_btnActionPerformed(ActionEvent e) {
        new NovoClienteFrame(this.cf).setVisible(true);
    }

    public RegistaEncomendaFrame(ConfiguraFacil cf, Configuracao config) {
        initComponents();
        this.cf = cf;
        this.config = config;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Pedro Moreira
    private void initComponents() {
        cliente_txt = new JTextField();
        jScrollPane1 = new JScrollPane();
        table1 = new JTable();
        novo_cliente_btn = new JButton();
        jScrollPane2 = new JScrollPane();
        jList2 = new JList<>();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        sair_btn = new JButton();
        registar_encomenda_btn = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regista Encomenda");
        Container contentPane = getContentPane();

        //---- cliente_txt ----
        cliente_txt.setText("Cliente");

        //======== jScrollPane1 ========
        {
            jScrollPane1.setViewportView(table1);
        }

        //---- novo_cliente_btn ----
        novo_cliente_btn.setText("Novo Cliente");
        novo_cliente_btn.addActionListener(e -> novo_cliente_btnActionPerformed(e));

        //======== jScrollPane2 ========
        {

            //---- jList2 ----
            jList2.setModel(new AbstractListModel<String>() {
                String[] values = {
                    "Item 1",
                    "Item 2",
                    "Item 3",
                    "Item 4",
                    "Item 5"
                };
                @Override
                public int getSize() { return values.length; }
                @Override
                public String getElementAt(int i) { return values[i]; }
            });
            jScrollPane2.setViewportView(jList2);
        }

        //---- jLabel1 ----
        jLabel1.setText("Pre\u00e7o");

        //---- jLabel2 ----
        jLabel2.setText("Desconto");

        //---- sair_btn ----
        sair_btn.setText("Sair");

        //---- registar_encomenda_btn ----
        registar_encomenda_btn.setText("Registar Encomenda");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(cliente_txt, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(novo_cliente_btn))
                                .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(sair_btn)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                            .addComponent(registar_encomenda_btn)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(novo_cliente_btn)
                        .addComponent(cliente_txt, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jLabel1)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)))
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(sair_btn)
                        .addComponent(registar_encomenda_btn))
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Pedro Moreira
    private JTextField cliente_txt;
    private JScrollPane jScrollPane1;
    private JTable table1;
    private JButton novo_cliente_btn;
    private JScrollPane jScrollPane2;
    private JList<String> jList2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JButton sair_btn;
    private JButton registar_encomenda_btn;
    // End of variables declaration//GEN-END:variables
}
